# Generated by Django 5.1.1 on 2025-10-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Talent'), (1, 'Client'), (2, 'Mentor'), (3, 'Admin')], default=0),
        ),
    ]
