GET http://localhost:8000/courses/api/


### admin user
POST http://localhost:8000/api/token/
Content-Type: application/json

{
    "email": "adeladanseun@gmail.com",
    "password": "adeladanseun"
}

### mentor user
POST http://localhost:8000/api/token/ 
Content-Type: application/json

{
    "email": "adeladansegun@gmail.com",
    "password": "adeladansegun"
}

###
GET http://localhost:8000/courses/api/course/

###
POST http://localhost:8000/courses/api/course/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwOTE0ODE1LCJpYXQiOjE3NjA5MTQ1MTUsImp0aSI6ImYyNGU1Y2U4MDZhYjRlMWRiNzJiNTFlMGM1MWQ1ZmVkIiwidXNlcl9pZCI6IjQifQ.j6fmkK6ywBNru_Z0mjcxswlTUNXg-8iz8RwbNKa1fAo

{
    "title": "Java",
    "description": "java programming language",
    "mentor": 3,
    "skills_covered": [1]
}

###
GET http://localhost:8000/courses/api/course/3/
