# Generated by Django 5.1.1 on 2025-10-10 21:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('job_type', models.IntegerField(choices=[(0, 'Full Time'), (1, 'Part Time'), (2, 'Contract'), (3, 'Freelance'), (4, 'Internship')], default=0)),
                ('experience_level', models.IntegerField(choices=[(0, 'Entry Level'), (1, 'Mid Level'), (2, 'Senior'), (3, 'Expert')], default=1)),
                ('location', models.CharField(blank=True, help_text='e.g., Remote, New York, NY.', max_length=200, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('budget_type', models.IntegerField(choices=[(0, 'Fixed Price'), (1, 'Hourly Rate'), (2, 'Monthly Salary'), (3, 'Milestone Based')], default=0)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator])),
                ('duration_weeks', models.PositiveIntegerField(blank=True, help_text='Expected duration in weeks (for contracts)', null=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Closed'), (3, 'Filled')], default=0)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(limit_choices_to={'role__in': [1, 2, 3]}, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
                ('required_skills', models.ManyToManyField(related_name='job_postings', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Contract', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_schedule', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'Completed'), (3, 'Cancelled'), (4, 'Disputed')], default=0)),
                ('progress', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('has_milestones', models.BooleanField(default=False)),
                ('communication_channel', models.URLField(blank=True, help_text='Whatsapp, LinkedIn, Slack, Zoom or any other communication link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='marketplace.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Completed'), (3, 'Approved'), (4, 'Paid')], default=4)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='marketplace.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('proposed_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_days', models.PositiveIntegerField(help_text='Estimated days to complete the project', validators=[django.core.validators.MinValueValidator(1)])),
                ('attachment', models.FileField(blank=True, help_text='Resume, similar projects, proposed solution', null=True, upload_to='proposal_attachments/')),
                ('status', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Under Review'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Withdrawn')], default=0)),
                ('client_notes', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Client rating of submitted proposal for future reference', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applier', models.ForeignKey(limit_choices_to={'role__in': [3, 0, 2]}, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='marketplace.jobposting')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('job', 'applier')},
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='proposal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='marketplace.proposal'),
        ),
    ]
