# Generated by Django 5.1.1 on 2025-10-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_mentor_alter_course_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.IntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Advanced')], default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Archived')], default=0),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Failed'), (3, 'Refunded')], default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.IntegerField(choices=[(0, 'Video'), (1, 'Article'), (2, 'Quiz'), (3, 'Assignment')], default=1),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.IntegerField(choices=[(0, 'Template'), (1, 'E-book'), (2, 'Cheat Sheet'), (3, 'Source Code'), (4, 'Tool'), (5, 'Other')], default=5),
        ),
    ]
