# Generated by Django 5.1.1 on 2025-10-10 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project_type', models.IntegerField(choices=[(0, 'Web Development'), (1, 'Mobile App'), (2, 'UI/UX Design'), (3, 'Digital Marketing'), (4, 'Video Production'), (5, 'Writing'), (6, 'Other')], default=6)),
                ('project_status', models.IntegerField(choices=[(0, 'Completed'), (1, 'In Progress'), (2, 'Not Started')], default=1)),
                ('visibility', models.IntegerField(choices=[(0, 'Public'), (1, 'Private'), (2, 'Link Only')], default=0)),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated list of technologies used', max_length=500, null=True)),
                ('client_name', models.CharField(blank=True, help_text='Leave blank or put your name if it belongs to you or client is private', max_length=200)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, help_text='Can link other git based related storage link', null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role__in': [0, 2, 3]}, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
                ('skills_used', models.ManyToManyField(blank=True, related_name='portfolio_items', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfolioitem')),
            ],
        ),
    ]
